# API 'Legal_Person_Classification.yaml'
openapi: 3.0.2
security: []
info:
  title: Looplex Legal Person Classification v3
  termsOfService: "https://docs.looplex.com.br/legal/termos-de-uso"
  contact:
    name: Developers Looplex
    email: developer@looplex.com.br
    url: "https://www.looplex.com.br"
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  x-logo:
    url: "https://www.looplex.com.br/img/logo-default.png"
    href: "/"
  description: >
    Fetch Legal Person Classifications
externalDocs:
  description: Find out how to create a GitHub repo for your OpenAPI definition.
  url: "https://github.com/Rebilly/generator-openapi-repo"
servers:
  - url: "https://apim.looplex.com/varas_foros"
    description: "Legal Person Classification Server"
paths:
  /v3/legalPersonClassifications:
    get:
      $ref: public@v3@legalPersonClassifications-get.yaml
  /v3/legalPersonClassifications/:id:
    get:
      $ref: public@v3@legalPersonClassifications@id-get.yaml

  /v3/deliberativeBody/:uuidLegalPersonClassification:
    get:
      $ref: public@v3@deliberativeBody@uuidLegalPersonClassification-get.yaml