title: Meta
type: object
description: "**Resource's metadata**"
properties:
  resourceType:
    type: string
    description: |
      **The resource type**<br />
      e.g. Case, Task, Entry, etc.
    example: <tipo_do_recurso>
  created:
    type: string <nullable>
    format: datetime
    example: <data_de_criacao_do_recurso>
    description: "**The resource creation date**"
  lastModified:
    type: string <nullable>
    format: datetime
    example: <data_de_atualizacao_do_recurso>
    description: "**The resource last update time**"
  location:
    type: string <nullable>
    example: <local_do_recurso>
    description: "**The resource url**"
  version:
    type: string
    example: <versao_do_recurso>
    description: "**The resource version**"