# API 'v2_task_template.yaml'
openapi: 3.0.2
security: []
info:
  version: 1.0.0
  title: Looplex Task Template
  termsOfService: "https://docs.looplex.com.br/legal/termos-de-uso"
  contact:
    name: Developers Looplex
    email: developer@looplex.com.br
    url: "https://www.looplex.com.br"
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  x-logo:
    url: "https://www.looplex.com.br/img/logo-default.png"
    href: "/"
  description: >
    API para parametrização de tasks
externalDocs:
  description: Find out how to create a GitHub repo for your OpenAPI definition.
  url: "https://github.com/Rebilly/generator-openapi-repo"
servers:
  - url: "https://apim.looplex.com/v2_task_template"
    description: "Task Template Server"
paths:
  /TaskTemplates/:id:
    get:
      $ref: task_templates\public@task_templates@id-get.yaml
  /TaskTemplates:
    get:
      $ref: task_templates\public@task_templates-get.yaml  
    post:
      $ref: task_templates\public@task_templates-post.yaml    
    patch: 
      $ref: task_templates\public@task_templates@id-patch.yaml

components:
  # Crie uma seção customizada para guardar trechos de texto
  x-descriptions:
    RamosJudicial: |
      **Indicação do tipo de caso, define o tipo de justiça ou o tipo de transação jurídica**<br />
      ADMINISTRATIVO<br />
      CONSULTIVO<br />
      JUDICIAL_ESTADUAL<br />
      JUDICIAL_FEDERAL<br />
      JUDICIAL_TRABALHISTA<br />
      MILITAR_ESTADUAL<br />
      ELEITORAL<br />
      MILITAR_UNIAO<br />
      CONTRATO<br />
      DUE_DILIGENCE_E_ANALISE_DOCUMENTAL<br />
      COBRANCA_EXTRAJUDICIAL<br />
      SOCIETARIO<br />
      ARBITRAGEM