# https://redocly.com/docs/openapi-visual-reference/info/
openapi: 3.1.0
info:
  version: 1.35.0
  title: "Looplex Case Management"
  termsOfService: "https://docs.looplex.com.br/legal/termos-de-uso"
  contact:
    name: Developers Looplex
    email: developer@looplex.com.br
    url: "https://www.looplex.com.br"
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  x-logo:
    url: "https://www.looplex.com.br/img/logo-default.png"
    href: "/"
  description: >
    Essa é a documentação da API Case Management
servers:
  - url: "https://apim.looplex.com/case-management/v1"
    description: "Case Management Server"
paths:
  
  # Authentication
  /token:
    post:
      $ref: v2_case-management\authentication\public@token-post.yaml
  
  # Case
  /cases/:id:
    get:
      $ref: v2_case-management\case\public@cases@uniqueId-get.yaml
    patch:
      $ref: v2_case-management\case\public@cases-patch.yaml
  /cases:
    get:
      $ref: v2_case-management\case\public@cases-get.yaml
    post:
      $ref: v2_case-management\case\public@cases-post.yaml

  # Entry
  /entries/:id:
    get:
      $ref: v2_case-management\entry\public@entries@entry_id-get.yaml
    patch:
      $ref: v2_case-management\entry\public@entries@entry_id-patch.yaml
  /entries:
    get:
      $ref: v2_case-management\entry\public@entries-get.yaml
    post:
      $ref: v2_case-management\entry\public@entries-post.yaml

  # Timesheet
  /timesheets:
    get:
      $ref: v2_case-management\timesheet\public@timesheets-get.yaml
    post:
      $ref: v2_case-management\timesheet\public@timesheets-post.yaml
  /timesheets/:id:
    get:
      $ref: v2_case-management\timesheet\public@timesheets@id-get.yaml

  # Client
  /clients:
    get:
      $ref: v2_case-management\client\public@clients-get.yaml
    post:
      $ref: v2_case-management\client\public@clients-post.yaml
  /clients/:id:
    get:
      $ref: v2_case-management\client\public@clients@client_id-get.yaml
    patch:
      $ref: v2_case-management\client\public@clients-patch.yaml

  # Legal service agreement
  /legalServiceAgreements:
    post:
      $ref: v2_case-management\legal_service_agreement\public@LegalServiceAgreement-post.yaml
    get:
      $ref: v2_case-management\legal_service_agreement\public@legalServiceAgreement-get.yaml
  /legalServiceAgreements/:id:
    get:
      $ref: v2_case-management\legal_service_agreement\public@legalServiceAgreements@id-get.yaml

  # Participant
  /participants:
    post:
      $ref: v2_case-management\participant\public@participants-post.yaml
    get:
      $ref: v2_case-management\participant\public@participants-get.yaml
  /participants/:id:
    get:
      $ref: v2_case-management\participant\public@participants@participant_id-get.yaml

  # LegalCategory (Natures)
  /legalCategories:
    get:
      $ref: v2_case-management\legal_category\public@legalCategories-get.yaml
    post:
      $ref: v2_case-management\legal_category\public@legalCategories-post.yaml
  /legalCategories/:id:
    get:
      $ref: v2_case-management\legal_category\public@legalCategories@legalCategory_id-get.yaml

  # Employees
  /employees:
    get:
      $ref: v2_case-management\employee\public@Employees-get.yaml
  /employees/:id:
    get:
      $ref: v2_case-management\employee\public@employees@employee_id-get.yaml

  # Claims
  /claims:
    get:
      $ref: v2_case-management\claim\public@claims-get.yaml
    post:
      $ref: v2_case-management\claim\public@claims-post.yaml
  /claim/:id:
    get:
      $ref: v2_case-management\claim\public@claims@claim_id-get.yaml
    patch:
      $ref: v2_case-management\claim\public@claims@claim_id-patch.yaml

  # Case Groups
  /caseGroups:
    get:
      $ref: v2_case-management\case_groups\public@caseGroups-get.yaml
  /caseGroups/:id:
    get:
      $ref: v2_case-management\case_groups\public@caseGroups@case_group_id-get.yaml