# https://redocly.com/docs/openapi-visual-reference/info/
openapi: 3.0.2
security: []
info:
  version: 2.0.0
  title: "Looplex Varas e Foros"
  termsOfService: "https://docs.looplex.com.br/legal/termos-de-uso"
  contact:
    name: Developers Looplex
    email: developer@looplex.com.br
    url: "https://www.looplex.com.br"
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  x-logo:
    url: "https://www.looplex.com.br/img/logo-default.png"
    href: "/"
  description: >
    Essa é a documentação de Varas e Foros
servers:
  - url: "https://apim.looplex.com/varas_foros"
    description: "Varas e Foros Server"
paths:
  # Varas e Foros
  /v2.1/ProximosNiveis/:id:
    get:
      $ref: v2_court_venue\court_venue\public@v2.1@ProximosNiveis@id-get.yaml
  /v2.1/HierarquiaFormatada/:id:
    get:
      $ref: v2_court_venue\court_venue\public@v2.1@HierarquiaFormatada@id-get.yaml
  /v2.1/court:
    get:
      $ref: v2_court_venue\court_venue\public@v2.1@court-get.yaml
  
components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: api_key
    auth_token:
      type: apiKey
      in: header
      name: auth_token
    basic_auth:
      type: http
      scheme: basic