# API 'v2_task_template.yaml'
openapi: 3.0.2
security: []
info:
  version: 1.0.0
  title: Looplex v2_task_template
  termsOfService: "https://docs.looplex.com.br/legal/termos-de-uso"
  contact:
    name: Developers Looplex
    email: developer@looplex.com.br
    url: "https://www.looplex.com.br"
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  x-logo:
    url: "https://www.looplex.com.br/img/logo-default.png"
    href: "/"
  description: >
    API para parametrização de tasks
externalDocs:
  description: Find out how to create a GitHub repo for your OpenAPI definition.
  url: "https://github.com/Rebilly/generator-openapi-repo"
servers:
  - url: "https://apim.looplex.com/v2_task_template"
    description: "v2_task_template Server"
paths:
# Endpoints dessa API
# Exemplo

  /TaskTemplates/:id:
    get:
      $ref: v2_task_template\task_templates\public@task_templates@task_template_id-get.yaml