# API 'Court_Venue_v3.yaml'
openapi: 3.0.2
security: []
info:
  version: 3.0.0
  title: Looplex Court Venue v3
  termsOfService: "https://docs.looplex.com.br/legal/termos-de-uso"
  contact:
    name: Developers Looplex
    email: developer@looplex.com.br
    url: "https://www.looplex.com.br"
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  x-logo:
    url: "https://www.looplex.com.br/img/logo-default.png"
    href: "/"
  description: >
    Endpoints de Court Venue v3
externalDocs:
  description: Find out how to create a GitHub repo for your OpenAPI definition.
  url: "https://github.com/Rebilly/generator-openapi-repo"
servers:
  - url: "https://apim.looplex.com/varas_foros"
    description: "Court Venue v3 Server"
paths:
  /v3/court/:id/nextLevels:
    get:
      $ref: v3_court_venue\court_venue\public@v3@court@id@nextLevels-get.yaml
  /v3/court/:id/hierarchy:
    get:
      $ref: v3_court_venue\court_venue\public@v3@court@id@hierarchy-get.yaml
  /v3/court/:id/formattedHierarchy:
    get:
      $ref: v3_court_venue\court_venue\public@v3@court@id@formattedHierarchy-get.yaml
  /v3/court/:id:
    get:
      $ref: v3_court_venue\court_venue\public@v3@court@id-get.yaml
  /v3/court/search_by_cnj:
    get:
      $ref: v3_court_venue\court_venue\public@v3@court@search_by_cnj-get.yaml
  /v3/court:
    get:
      $ref: v3_court_venue\court_venue\public@v3@court-get.yaml
  /v3/court/search:
    get:
      $ref: v3_court_venue\court_venue\public@v3@court@search-get.yaml
  /v3/court/:id/children:
    get:
      $ref: v3_court_venue\court_venue\public@v3@court@id@children-get.yaml
  /v3/court/children:
    get:
      $ref: v3_court_venue\court_venue\public@v3@court@children-get.yaml
  /v3/court/list:
    get:
      $ref: v3_court_venue\court_venue\public@v3@court@list-get.yaml