# API 'Contract_Classification.yaml'
openapi: 3.0.2
security: []
info:
  title: Looplex Contract Classification v3
  termsOfService: "https://docs.looplex.com.br/legal/termos-de-uso"
  contact:
    name: Developers Looplex
    email: developer@looplex.com.br
    url: "https://www.looplex.com.br"
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  x-logo:
    url: "https://www.looplex.com.br/img/logo-default.png"
    href: "/"
  description: >
    Fetch Contract classifications
externalDocs:
  description: Find out how to create a GitHub repo for your OpenAPI definition.
  url: "https://github.com/Rebilly/generator-openapi-repo"
servers:
  - url: "https://apim.looplex.com/varas_foros"
    description: "Contract Classification Server"
paths:
  /v3/contractClassifications:
    get:
      $ref: public@v3@contractClassifications-get.yaml
  /v3/contractClassifications/:id:
    get:
      $ref: public@v3@contractClassifications@id-get.yaml

  /v3/contractTypes/:uuidContractClassification:
    get:
      $ref: public@v3@contractTypes@uuidContractClassification-get.yaml