# API 'Occupations.yaml'
openapi: 3.1.0
security: []
info:
  version: 1.0.0
  title: Looplex Occupations
  termsOfService: "https://docs.looplex.com.br/legal/termos-de-uso"
  contact:
    name: Developers Looplex
    email: developer@looplex.com.br
    url: "https://www.looplex.com.br"
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  x-logo:
    url: "https://www.looplex.com.br/img/logo-default.png"
    href: "/"
  description: >
     APIs de Occupations
externalDocs:
  description: Find out how to create a GitHub repo for your OpenAPI definition.
  url: "https://github.com/Rebilly/generator-openapi-repo"
servers:
  - url: "https://apim.looplex.com/standards/v1"
    description: "Occupations Server"
paths:

# Endpoints dessa API
  /Occupations:
    get:
      $ref: occupation\public@Occupations-get.yaml
  /Occupations/:id:  
    get: 
      $ref: occupation\public@Occupations@Id-get.yaml