# https://redocly.com/docs/openapi-visual-reference/info/
openapi: 3.0.2
security: []
info:
  version: 2.0.0
  title: "Looplex Court Venue"
  termsOfService: "https://docs.looplex.com.br/legal/termos-de-uso"
  contact:
    name: Developers Looplex
    email: developer@looplex.com.br
    url: "https://www.looplex.com.br"
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  x-logo:
    url: "https://www.looplex.com.br/img/logo-default.png"
    href: "/"
  description: >
    Essa é a documentação de Court Venue
servers:
  - url: "https://apim.looplex.com/courtVenue"
    description: "Court Venue Server"
paths:
  # Court Venue (Varas e Foros)
  /venues/:venue_id:
    get:
      $ref: .\paths\court_venue\court_venue\public@venues@venue_id-get.yaml
  /venues:
    get:
      $ref: .\paths\court_venue\court_venue\public@venues-get.yaml
  /subjectTags:
    get:
      $ref: .\paths\court_venue\tags\public@subjectTags-get.yaml
  /tags:
    get:
      $ref: .\paths\court_venue\tags\public@tags-get.yaml
  /tags/:tag_id:
    get:
      $ref: .\paths\court_venue\court_venue\public@tags@tag_id-get.yaml
components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: api_key
    auth_token:
      type: apiKey
      in: header
      name: auth_token
    basic_auth:
      type: http
      scheme: basic